### ISSUE TITLE
Color key for transcriptions and "n" (for notes) need to be implemented

### ISSUE THREAD

**Issue by foxm** [blakearchive/archive#138]

**Comment by queryluke** [comment]
@foxm How should this look and/or work? Is there an example on the current site?

**Comment by foxm** [comment]
@queryluke here's an example: http://localhost:8002/blake/copy/letters?objectId=1118

the link Color key... should take you to a rendition of this: http://www.blakearchive.org/blake/key.html

'n' should open editors' notes for object (different from editors' notes for copy, which are already being shown in the info box)

**Comment by queryluke** [comment]
@foxm  Could these pop up in a [bootstrap modal](http://getbootstrap.com/javascript/#modals), instead of a link to a static page? Or do you want the static page?

And I'm still a bit unclear about the editors' notes. There are the "Editors' Notes" accordion panel in the info tray. Clicking on this expands that section and shows 2 items, "Object Notes" & "Textual Notes". These change when you switch between objects. Are these the notes you're referring to? If so, you mean you want the [n] to open this accordion panel?

Or is there a different set of notes I should look for?

**Comment by foxm** [comment]
@queryluke yeah, a modal would work. 

the notes for the transcriptions are within <note> tages within the transcriptions (<phystext>) in the BADs.

**Comment by queryluke** [comment]
making a new ticket for the object notes
