### ISSUE TITLE
for all tabs except objects in copy, remove big work title and put work title above every handprint in bold and all caps

### ISSUE THREAD

**Issue by foxm** [blakearchive/archive#183]

**Comment by foxm** [comment]
for objects in copy, just remove big work title. and no need to put in work titles above every handprint

**Comment by queryluke** [comment]
This is a 2 pronged issue. 

First is the data retrieved in teh objects-from-same-X query. Right now it returns objects, which has copy titles, and their own titles. But it does not have work titles. This will need to be added to the object data model.

The second issue is css. The checkbox/selection for comparison objects is affixed to the top-right corner of the handprint. Since title string will vary in size, we need to rework the divs that this checkbox icon is attached to. Not terribly difficult, but I don't want to start on it until the work titles are available.

**Comment by queryluke** [comment]
Related to #199, pulling the info from that here

> All handprints in objectsFromSame tabs need to have work titles in bold. Some don't at the moment.
>For virtual groups, work titles in ovp need to have virtual group title and object title (ex: Illustrations to the Bible and on the next line Enoch Walked with God). Also for virtual groups, the handprints in Objects in Group need to have object titles boldfaced and below those there should be the object numbers and Butlin numbers. Currently titles and object numbers are on one line.
