### ISSUE TITLE
implement static pages

### ISSUE THREAD

**Issue by foxm** [blakearchive/archive#195]
@queryluke hey luke, i started this on the branch static. i know it's probably not the best way to do things because i combine angular and jquery, but it might be sufficient. let me know what you think whenever you get a chance. no rush--i know you're working on other things

**Comment by foxm** [comment]
tried implementing this with ng-bootstrap-submenu:

https://github.com/ryanlangton/ng-bootstrap-submenu/blob/master/example.html

**Comment by queryluke** [comment]
@foxm Sorry, I've been away at training this week, so I've been limited in what I can do this week.

I took a quick look at the code on this branch. Here are my thoughts:

RE: left subnav
This is a conceptual choice. If it makes sense for users to sequentially move through these pages from "What's new -> Related Sites", then I'd keep the subnav. The subnav elicits a group of pages that the user can/should navigate within.

However, if all of the pages in the footer are conceptually different, then remove the left navigation.

RE: executing the static pages
Depends on if you keep or remove the subnav. Using ng-include is fine., but instead of the jquery scripts, all your should need is to pass the content name to the controller. For example, on the subnav add  ```ng-click="staticpage.changeContent(update)"```

Then in the controller
```
vm.changeContent = function(staticpage){
    vm.initialSelection = staticpage
}
```

However, if you get rid of the subnav, this is unecessary
