### ISSUE TITLE
internal links on static pages

### ISSUE THREAD

**Issue by foxm** [blakearchive/archive#202]
internal links leading back to the same static page need to be relative to the active submenu page, not the initial (first submenu) page and they need to be adjusted for the top banner (currently when you click on an internal link it begins the page behind the banner--it should begin it below the banner)
   ----Glossary, General Bibliography, Specific Bibliography

internal links need to be edited to reflect the new site address

internal links in All Update need to go on separate lines (some are doubling up)

image links in Latest Update and Contributing Collections need to be corrected

**Comment by foxm** [comment]
@queryluke hey luke, i'm having a hard time figuring out how to deal with anchors in the way i've set things up for the static pages. when you get a chance, could you look at this? i'm betting it's an easy fix that i just can't see. 

if you go to About Blake, then Glossary, you'll see anchor links all over. but because Glossary is a page within a page, the anchor links don't lead to where they should. i tried to use anchorScroll with a scrollTo function but it didn't work.

**Comment by queryluke** [comment]
@foxm 

There were 2 issues here. 

1. Since this is a subpage, all those hrefs should have targeted the url, but this would have resulted in a reload of the page. So it wasn't ideal.
2. The other issue is that ```<a name="#id"></a>``` is depreciated in html5. Most modern browsers react oddly to it, and angular wasn't targeting the divs correctly with anchorScroll, which is why, I assume, you couldn't get it to work on your end. W3Schools recommends using ids instead.  I did a find/replace on all the ```name=""``` and changed them to ```id=""```, so that issue is solved. But if there are other pages that use ```<a name="">``` you'll want to find/replace those as well.

Luckily, I had already built out a **scroll-to-element** directive for the search ui. I did some tweaking on it and it works for both uses now. 

You can replace all the ```<a href="#tagID">``` with ```<a scroll-to-element="#tagID" offset="50">```

**#tagID** is the ID of the ```<a>``` tag you want to scroll to.
**offset** is the window offset. Since we're using a fixed top navigation, we need to offset 50px, the height of the top nav.

That should get you started on resolving this. Let me know if you run into further issues.
