### ISSUE TITLE
only show 'n' and 'Color key for transcriptions' if necessary

### ISSUE THREAD

**Issue by foxm** [blakearchive/archive#249]

**Comment by queryluke** [comment]
I've permanently hidden the [n], as it hasn't ever done anything. As noted in previous issues, all object notes are being displayed in the Editors' Notes section under a heading "Object Notes." In order to have the object notes in line with the text transcription, we will need to write the necessary scripts to parse out the transcript xml. As it stands now, we're just spitting out the tei content. #166 is a placeholder/reminder for writing these scripts
