### ISSUE TITLE
zoom bug

### ISSUE THREAD

**Issue by foxm** [blakearchive/archive#255]
@queryluke luke, there seems to be a minor bug with zoom. sometimes the image within the magnifying glass doesn't line up with the target image. i think the bug initiates when you run your mouse over the target area before the image loads. i'm not quite sure because when you reload the page the magnifying glass works just fine. it's hard to replicate.

**Comment by queryluke** [comment]
@foxm 

I made the zoom feature toggle-able, with a tooltip that shows "Mouse over the image" after you click the Zoom button.

The reason is that this script takes a lot of memory (specifically in tracking the mouse movement and making calculations on the coordinates) and after doing some browser diagnostics, I deemed it best not to have it on constantly.

And by having it off on the initial page load it fixes this error.

Luke

**Comment by foxm** [comment]
@queryluke looks good, but when zoom is on and you go to the next or previous object, the alignment problem crops up again. let's just have zoom get turned off (if it's on) when the user changes objects (goes to next or previous or clicks on a handprint below)

**Comment by queryluke** [comment]
@foxm 

Ok, that helped narrow down the root of the problem. Try again. (Zoom still stays on between object changes, but the weird offset is fixed).
