### ISSUE TITLE
<note> for <date>,<compdate>,<objectorder>,<pennednumbers>, and others is not showing in copy information

### ISSUE THREAD

**Issue by foxm** [blakearchive/archive#293]

**Comment by queryluke** [comment]
@foxm 

Look at my [latest commit](https://github.com/blakearchive/archive/commit/19c2a98e200bdb9e8123f0401d908e0e7f31aced)

The issue is, for a note to appear, we need the angular logic to look for it.

The main question: should every field be checked for notes? If that's the case, I'll make a new directive that we can reuse (it'll clean up the copy-information.html this page as well)

**Comment by foxm** [comment]
yeah, every field should be checked
