### ISSUE TITLE
virtual group objects retain their own compdate on import

### ISSUE THREAD

**Issue by foxm** [blakearchive/archive#305]
@queryluke i noticed one sorting issue:

in this virtual group: http://localhost:8002/blake/copy/gravepd?descId=but614r.1.penc.01

the objects are sorted according to object number, but they should be sorted according to composition_date_value, right? it's fine the way it is, i think, though i'll have to ask @joeafletch. but i'm just checking with you, luke, because you'd mentioned these would be sorted by print_date_value, then comp_date_value, then object number. it doesn't seem to be the case here.

**Comment by queryluke** [comment]
That's because they have no copy_composition_date_value, it's null in the database. Keep in mind there are 2 places to pull the comp/print date.

1. From the source, which is just a json dump. The main issue with using this is that only virtual groups have it.
2. From the copy_comp/print_date_string (or value). 

So in the display, you're pulling from the former. The database pull is on the latter. We can't make a database sort on the former because it's not normalized.

I don't know enough about the python scripts, but I assume there would be a way to make virtual work objects use their own comp date.

**Comment by queryluke** [comment]
@nathan-rice We've got the sort order set. But for virtual work objects, seems those should retain their own compdate (I assume we'll need the int, _value, and _string).

You also mentioned using joins to pull in information from the copy. Whatever efficiencies you want to make is your call.

**Comment by foxm** [comment]
ok, let's have them retain their own compdates, but let's hold off on sorting them that way. they may be sorted correctly already
