### ISSUE TITLE
rotate is not resizing the window when it needs to

### ISSUE THREAD

**Issue by foxm** [blakearchive/archive#351]
example:

http://blake.lib.unc.edu/blake/copy/bb466.2?descId=bb466.2.comb.07

**Comment by queryluke** [comment]
@foxm Please review branch: [*issue153*](https://github.com/blakearchive/archive/tree/issue351)

Landscape image heights are now bound by a maximum width based on the height of the parent element. I.e., instead of the OVP growing and shrinking when a landscape image rotates, the landscape images are smaller and rotate within the OVP.

Although the image is smaller, the rotate button is much more responsive (before it was dragging due to all the calculations). And, IMHO, the OVP resize was a little jarring.

Let me know and I can merge.

**Comment by queryluke** [comment]
Oh, and this might fix #353, or at least make it easier to fix

**Comment by foxm** [comment]
great!

**Comment by foxm** [comment]
looks like this has cropped back up again.
