### ISSUE TITLE
Laocoön popout text

### ISSUE THREAD

**Issue by Grantglass** [blakearchive/archive#360]
if you click on the title text on the top of the Laocoön and you get the pop-out; the text that you see LAOCOÃ¶N instead of Laocoön.

**Comment by queryluke** [comment]
I think the issue is the work.csv file. But I've confirmed that it looks this way in the database, so there isn't really anything I can do. The first thing to try would be to replace the umlaut o in `works.csv` with the unicode character code `&#246;`, re-import and see if that fixes it. @nathan-rice  does that sound like a good first try to you?

**Comment by nathan-rice** [comment]
The problem is the unicode encoding of the documents.  Everything should be in utf-8 but right now documents are a mix of utf-8 and latin-xxxx versions, so one encoding doesn't render everything properly.  For best results, configure your editor to use the utf-8 encoding.

**Comment by foxm** [comment]
tried &#246; but that didn't work. works.csv is in utf-8.

**Comment by foxm** [comment]
tried `&ouml;` too
