### ISSUE TITLE
script that makes blake-relations.csv commutative

### ISSUE THREAD

**Issue by ba001** [blakearchive/archive#363]
this can be part of the script that populates blake-relations.csv

here's an example of an object for which we've forgotten to include all its Objects With a Similar Design:

http://london.lib.unc.edu/blake/copy/mhh.f?descId=mhh.f.illbk.04

**Comment by foxm** [comment]
@joeafletch joe, referencing you here so we don't forget about this example before launch

**Comment by joeafletch** [comment]
@foxm I'm not sure I follow--this example looks to be working as it's supposed to. Did you fix it?

**Comment by foxm** [comment]
@queryluke i had noticed that the reverse relationships for the Objects with a Similar Design were not showing. but now i can't see those objects for some reason

**Comment by joeafletch** [comment]
@foxm @queryluke I'm going through the blake-relations.csv currently and adding new copies for s-inn. It's going to take a while, since all the same-matrix relationships between s-inn and songsie objects were never indicated, and they need to be. That means the same-matrix column for every single object of all copies of s-inn and songsie needs to be modified, in addition to the (~93) new rows needed for the three copies of s-inn we're adding. If there was a way to automate this, I'd be grateful. Because it's a slog.
