### ISSUE TITLE
london.lib and blake.lib open up at different zoom levels

### ISSUE THREAD

**Issue by foxm** [blakearchive/archive#364]
the fonts, etc. are bigger on london.lib than on blake.lib initially. i was trying to figure out why the subtitles in the new windows "Textual Transcription," "Editors' Notes, etc." was showing on blake.lib and not london.lib and noticed this issue. i think we should set london.lib to blake.lib's settings

**Comment by queryluke** [comment]
Do you mean the "zoom" setting in Chrome (the browser)? I.e., click on the vertical ellipsis in the upper-right of Chrome, in the dropdown menu there is a zoom option.

If this is what you mean, then there is nothing in the angular code that sets the zoom level of the browser. That option is controlled by Chrome. If the default settings were off between the two sites, it's because Chrome stores that setting on a per-subdomain basis. So every site you visit can have a different level of magnification. It's not global for all tabs in the browser.

**Comment by foxm** [comment]
ah, ok, it must be storing it differently for each of the two sites
