### ISSUE TITLE
Copy Replication on Work Pages for Illuminated Books

### ISSUE THREAD

**Issue by joeafletch** [blakearchive/archive#381]
The textual lists of "All Known Copies" are getting triplicated on all work pages for illuminated books--they should only be listed once.

Also, the related copies should not appear in the "All Known Related Items" lists.

**Comment by joeafletch** [comment]
@queryluke I see that the redundancies have been eliminated in the All Known Copies section--thanks--but we still need to eliminate repeating that list of copies in the All Known Related Items section (below the known copies section), since that relationship is covered in the All Known Copies.

**Comment by foxm** [comment]
i think i got rid of the repeated copies, and i changed the comp dates to print dates. copy items should be ordered by print date, then copy letter.

and it looks like the Copies that aren't in the Archive need to be moved up to All Known Copies from All Known Related Works.

**Comment by foxm** [comment]
the problem is that in our info files, the related copies that are in the archive have a `<link>` and link type associated with them, but not the copies that aren't in the archive. can we just do some string matching for the latter?

**Comment by queryluke** [comment]
Since we're limited on time, I'll try to hack something together. I can't guarantee it will work for all related works.

But here is my recommended template for relationships for the future.

```
<relationship type="(object | copy | work)">
  <link>(linkId | false)</link>
  <title>title string</title>
  <date>date</date>
  <information>
    <line>...</line>
    <line>...</line>
  </information>
</relationship>
```

That may not cover all your use cases. It's just a starting point. But when that gets translated into json, it's much easier to deal with. I can limit the foreach loop by relationship type (and note that EVERY relationship has a type, not just ones with links). I can programmatically add the link. I can sort by a date attribute. It's a toss-up on if you should separate your "information" by line. 100% by the book, you should not. But depending on your needs, you could. Anyway, just keep this in mind for future use.

**Comment by foxm** [comment]
@queryluke @joeafletch thanks. for now, a hack is fine. and if it doesn't work for all, i think that's fine, too. i'd say it's really just copies that need to be all grouped separately and ordered properly.
