### ISSUE TITLE
Songs of Innocence info page missing related copies and related items lists

### ISSUE THREAD

**Issue by joeafletch** [blakearchive/archive#395]
I just checked the info file and the lists are there, so not sure what is preventing them from getting displayed.

**Comment by queryluke** [comment]
It's not in the database either. Meaning it's the import scripts...

**Comment by queryluke** [comment]
AHA! So I actually got the debugging working and found this:

```
ERROR:import:info file does not exist: gates-sexes.info
ERROR:import:info file does not exist: s-inn.info
ERROR:import:info file does not exist: but435.info.xml
ERROR:import:info file does not exist: btu538.info.xml
ERROR:import:info file does not exist: 
```
The lack of related_works is caused by typos in the works.csv, 3rd to last column where you identify the info filename.

So it looks like the first 2 just need `.xml` on the end.
The 3rd one should be `bb` not `but`
The 4th has the `u` and `t` switched
The last one is the exhibits entry, which shouldn't have an info file

**Comment by foxm** [comment]
fixed
