### ISSUE TITLE
not urgent: make menu dropdown scrollable if it goes beyond height of browser

### ISSUE THREAD

**Issue by foxm** [blakearchive/archive#398]
make the height of your browser shorter and hit Drawings and Painting in the menu. notice how it goes beyond the base of the browser. it would be good to make this scrollable in case people are using small laptops

**Comment by queryluke** [comment]
To make this possible, you're going to need to give the menu a fixed height, which is going to make ALL menu dropdowns the same size.

A small laptop (10") has the same screensize/resolution as an landscape ipad without retina display. When I view the size in an ipad emulator the dropdown menu doesn't go past the bottom of the screen.

As I make my screen smaller the tallest that menu ever gets is 816px. By the time the screen gets to 900w, the height of that menu jumps down to 700. So it would even work on a 900x700 screen. So really this is an edge case for someone who has manually made there window size ~800x800. IMHO that's a non issue, no screens are like that.

**Comment by foxm** [comment]
ok, yeah, we can forgo this one, but i'm not sure i'm understanding you. on my 15" laptop, if i take expand the browser all the way and then take off a couple inches from the bottom, that's when it starts to go past the bottom of that menu (Drawings and Paintings). and i believe i'm on the standard resolution. but yeah, let's just forget this one for now

**Comment by foxm** [comment]
here's a screenshot
<img width="1280" alt="screen shot 2016-12-09 at 9 39 36 am" src="https://cloud.githubusercontent.com/assets/3813087/21052534/7ef07874-bdf3-11e6-9f61-ba70efe38c83.png">

**Comment by queryluke** [comment]
[My 13" on standard resolution](https://drive.google.com/open?id=0BxLeDaHVwlDzMDNNVjZUbTZheDg), Looks like firefox adds some extra padding to the window

But my point here is that you've manually adjusted your screen size. You can make that window larger and get to those links. It's not convenient but now impossible. 

But since you're only missing about 15px worth of content. You could reduce the padding on the header elements (Pencil Sketches, Pen and Ink...) and menu `<li>` elements, making the vertical gaps between each link tighter. That would definitely get you that extra little bit.

**Comment by foxm** [comment]
yeah, this is fine
