### ISSUE TITLE
not urgent: tei-line-note width inconsistent

### ISSUE THREAD

**Issue by foxm** [blakearchive/archive#400]
in the transcriptions for:

http://london.lib.unc.edu/blake/copy/bb74.1?descId=bb74.1.ms.03

the first 9 lines are indented too much. it looks like in the space between the numbers 1-9 and the first word of the line, there's a td.tei-line-note that's too wide, wider than the very narrow ones between, say, 12 and 'In', on line twelve.

**Comment by queryluke** [comment]
Ha! Well this is interesting, but it just goes to show that kerning matters.

In your current site, you're using Times New Roman. The spacing between the letters is slightly different than Lato (the font on the new site). Primarily due to the face the TNR is serif and Lato is sans-serif.

In css/tei.css, you can add `font-family: "Times New Roman", Times, serif;` to the `.tei-table` element (line 106). But I don't know if you actually want to uses TNR.

You may want to discuss with the editors, as using Lato might require re-spacing everything.

**Comment by foxm** [comment]
sigh. i can't wait to put this aside for a while--haha. changed to Times

**Comment by foxm** [comment]
hmm, somehow this cropped up again even with Times

**Comment by foxm** [comment]
changed back to Lato--seems to have fixed it. not sure how that happened
