### ISSUE TITLE
title in copy information not showing up

### ISSUE THREAD

**Issue by foxm** [blakearchive/archive#407]
http://london.lib.unc.edu/blake/copy/bb467.1?descId=bb467.1.comeng.03

in the BAD it reads: 

```
<objtitle>
          <title>William Hayley, *An Essay on Sculpture*</title>
        </objtitle>
```

**Comment by foxm** [comment]
also, the problem with the colon on its own line for roles has cropped up here for some reason, but not in other places

**Comment by queryluke** [comment]
The part of the BAD you've linked in your comment is part of the copy source section:
```
<source>
      <objdescid>
        <objtitle>
```

But tou need to look at how these strings are generated, **directives/copy-information/copy-information.html**, line 11:

`<dd ng-bind-html=" info.getHeader().filedesc.titlestmt.title.main['#text'].trim() | markdown | highlight:info.highlight"></dd>`

`filedesc.titlestmt.title.main` in the BAD is
```
    <filedesc>
      <titlestmt>
        <title reg="An Essay on Sculpture">
          <main>
            <author>William Hayley</author>, An Essay on Sculpture</main>
             ....
          </title>
```
You've got an `author` element around William Hayley, which gets parsed as another attribute in the copy model. So, either edit the correct part of the BAD, or change line 11 to use a different target on the copy model:
`info.getSource().objdescid.objtitle.title['#text']`

I usually refrain from making these types of edits because I don't know enough about the BAD structure to know where I should be pulling the information from.

**Comment by foxm** [comment]
the title in copy information should be coming from the copy source section

**Comment by foxm** [comment]
but i guess for now i can change that other title tag

**Comment by queryluke** [comment]
If that's the case just change the copy information code

**Comment by foxm** [comment]
right, all set
