### ISSUE TITLE
deploy prod error

### ISSUE THREAD

**Issue by foxm** [blakearchive/archive#413]
@queryluke luke, do i need to change something in the config for deploying to prod now that we're live?

i'm getting this error:

(Backtrace restricted to imported tasks)
cap aborted!
Errno::ECONNREFUSED: Connection refused - connect(2)

Tasks: TOP => git:check => git:wrapper
(See full trace by running task with --trace)
The deploy has failed with an error: Connection refused - connect(2)

**Comment by queryluke** [comment]
Nope, I think this was just unfortunate timing. We were doing one final restart of the server before notifying you all that everything was set. Try again and let me know if you get the same error.

**Comment by foxm** [comment]
yep, worked now. thanks

**Comment by afmccune** [comment]
Love the new site!

I just noticed that the "Blake Quarterly" link points to current issues rather than the BQ archive--is that intentional?

Adam

On Dec 12, 2016, at 10:33 AM, foxm <notifications@github.com<mailto:notifications@github.com>> wrote:


@queryluke<https://github.com/queryluke> luke, do i need to change something in the config for deploying to prod now that we're live?

i'm getting this error:

(Backtrace restricted to imported tasks)
cap aborted!
Errno::ECONNREFUSED: Connection refused - connect(2)

Tasks: TOP => git:check => git:wrapper
(See full trace by running task with --trace)
The deploy has failed with an error: Connection refused - connect(2)
