### ISSUE TITLE
slowness

### ISSUE THREAD

**Issue by ba001** [blakearchive/archive#421]
@queryluke one of our members at rochester reported this:

"I was looking at the Dante illustrations this morning, then wanted to go to the letters. Gold bar gradually moved, then stopped altogether just before it made it all the way across the page. Letters have now appeared, a few minutes later."

i've noticed this occasionally happening, too, in random places.

**Comment by queryluke** [comment]
There is very little I can do to debug issues like this. If you give me a timestamp (within a minute at least) of when the issue happened, I can peruse the logs and look for errors. Or if you are noticing this happening, open the dev console and see if there are any javascript errors.

I suspect the problem is the mixture of handprint file size and slow connections. There are 53 handprints on the letters work page. Each handprint requires a download of ~344kb. 344 * 53 / 1028 = 17.7 mb. That can take some time on a slower connection.

**Comment by ba001** [comment]
Just before 8:42am today, according to Sarah at Rochester.

**Comment by queryluke** [comment]
not seeing anything offending

**Comment by ba001** [comment]
@queryluke when you get a chance (or when you return from the holidays), can you check the logs from around 3:00 to 3:06 today (12/26). where are the logs located by the way? i was experiencing extreme slowness. the home page didn't load for about 5 minutes. at the moment i'm trying to navigate in compare mode, and the thing is totally stalled

**Comment by ba001** [comment]
actually, now nothing will load at all (3:08)
