### ISSUE TITLE
deploy different branches on qa

### ISSUE THREAD

**Issue by ba001** [blakearchive/archive#428]
@queryluke hey luke, could you modify the deploy scripts so that i can deploy different branches on qa? not different data branches. i know i can do that by seeding a different branch. but i'd like to deploy a different branch of the code on qa, if possible

**Comment by queryluke** [comment]
I wouldn't recommend it. The python26 branch is the one that actually lives on the servers. Due to inconsistencies between python 2.6 and 2.7, if you accidentally deploy a python 2.7 version of the code, the server will generate errors.

So you'd have to create your new branch from python26, and merge it back into master...but that could overwrite the master code with the python26 changes...meaning you'd no longer have a working python2.7 version of the code. It could get messy really quickly.

Is there a reason local development won't suffice?

**Comment by ba001** [comment]
Ok. I just checked in and deployed a big change, getting rid of the blake/. I wanted to test it on qa first. I realized I could revert a merge pull request pretty easily, so I just merged the branch I was working on first. I guess I can do that in the future
