### ISSUE TITLE
new services.py

### ISSUE THREAD

**Issue by roastduckalamode** [blakearchive/archive#46]
@nathan-rice I merged the code cleanup and your files and am running into issues with the new services.py file. I tried rolling back master to before the code cleanup, then pulled down to london and my local dev (this would be the commit with just your search changes), and I got the same errors. The console was logging a 500 error, but I can give you the full pri

Which solr instance are you pointing to? In Dean's and my file we've removed the solr variable, which should result in the service pointing at "ctools-dev.its.unc.edu:8983/...". When I change that var to lib_dev or lib_prod, I get access denied (obviously because we don't have the right auth). 

I've retained a copy of your update services file in services_new.py, and a copy of the update search view as search_new.html. So this gets resolved I'll restore those files. the search controller just has a simple change adding ".results" to line 75 and 90. (Just noting this so I don't forget)

**Comment by nathan-rice** [comment]
It would be helpful if you could include the stack trace produced by the 500 error.

I pulled your changes, everything appears to be working on my local dev setup.

**Comment by roastduckalamode** [comment]
Here is what I'm seeing:

```
Traceback (most recent call last):
  File "/Users/lukeluke/Sites/blake/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/lukeluke/Sites/blake/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/Users/lukeluke/Sites/blake/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/lukeluke/Sites/blake/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/lukeluke/Sites/blake/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/lukeluke/Sites/blake/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/lukeluke/Sites/blake/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/lukeluke/Sites/blake/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/lukeluke/Sites/blake/archive/blakearchive/api.py", line 16, in query
    results = blake_data_service.query_objects(config)
  File "/Users/lukeluke/Sites/blake/archive/blakearchive/services.py", line 102, in query_objects
    work_results = work_query(config)
  File "/Users/lukeluke/Sites/blake/archive/blakearchive/services.py", line 58, in work_query
    results["title"]["results"] = [transform_result(result) for result in solr_results]
  File "/Users/lukeluke/Sites/blake/archive/blakearchive/services.py", line 44, in transform_result
    new_result["text"] = json.loads(result["text"])
KeyError: 'text'
```

**Comment by nathan-rice** [comment]
This problem is being caused by your Solr schema lacking a required field.  I've attached my solr schema.xml code so you can update your end.  Might not be a bad idea to include the solr schema.xml document in the project/git so we can sidestep this issue in the future. 

One thing that is absolutely necessary is that you re-run all the import scripts when you update the site (at least after I make information architecture changes).  That includes import.py, homepageimport.py and solrimport.py.

`<?xml version="1.0" ?>


<schema name="example core zero" version="1.1">

   <fieldtype name="string"  class="solr.StrField" sortMissingLast="true" omitNorms="true"/>
   <fieldType name="long" class="solr.TrieLongField" precisionStep="0" positionIncrementGap="0"/>
   <fieldType name="text" class="solr.TextField" omitNorms="false">
     <analyzer>
       <tokenizer class="solr.StandardTokenizerFactory"/>
       <filter class="solr.StandardFilterFactory"/>
       <filter class="solr.LowerCaseFilterFactory"/>
     </analyzer>
   </fieldType>

  
  <field name="id"        type="long"   indexed="true"  stored="true"  multiValued="false" required="true"/>
  <field name="_version_" type="long"     indexed="true"  stored="true"/>
  <field name="dbi" type="text" indexed="true" stored="true" multiValued="false"/>
  <field name="desc_id" type="text" indexed="true" stored="true" multiValued="false"/>
  <field name="title" type="text" indexed="true" stored="true" multiValued="false"/>
  <field name="bentley_id" type="string" indexed="true" stored="true" multiValued="false"/>
  <field name="components" type="text" indexed="true" stored="true" multiValued="false"/>
  <field name="illustration_description" type="text" indexed="true" stored="true" multiValued="false"/>
  <field name="text" type="text" indexed="true" stored="true" multiValued="false"/>
  <field name="copy_title" type="text" indexed="true" stored="true" multiValued="false"/>
  <field name="work_title" type="text" indexed="true" stored="true" multiValued="false"/>
  <field name="work_medium" type="text" indexed="true" stored="true" multiValued="false"/>
  <field name="copy_composition_date" type="long" indexed="true" stored="true" multiValued="false"/>
  <field name="copy_print_date" type="long" indexed="true" stored="true" multiValued="false"/>
  <field name="copy_header" type="text" indexed="true" stored="true" multiValued="false"/>
  <field name="copy_institution" type="text" indexed="true" stored="true" multiValued="false"/>
  <field name="copy_id" type="text" indexed="true" stored="true" multiValued="false"/>
 
 <uniqueKey>id</uniqueKey>

 
 <defaultSearchField>text</defaultSearchField>

 
 <solrQueryParser defaultOperator="OR"/>
</schema>
`
