### ISSUE TITLE
boolean 'preview' column in works.csv

### ISSUE THREAD

**Issue by ba001** [blakearchive/archive#475]
@joeafletch do we need a 'preview' column in works.csv that indicates which works should be displayed only on development (london)? that way we can keep a master works.csv, but the works with the preview designation will not get displayed on production, only on development.

@nathan-rice does this sound feasible?

**Comment by nathan-rice** [comment]
I could certainly add that property to the model easily enough, but then we have to add more configuration code to the codebase to differentiate between development and live.  It would be more elegant if you maintained the differences using separate git branches.

**Comment by ba001** [comment]
@nathan-rice @joeafletch given the way we work, i think it would be best to go the route of using a 'preview' column. we want to maintain a 'preview' branch that's always showing on london. if we maintained branches for every work/copy, we'd have to merge all of them into preview periodically, and we'd have to merge each one we want to publish into master. it would get hairy, and i'm afraid there'd be more potential for user error (someone might upload the wrong file to the wrong branch, etc.) it would much easier for us to maintain one 'preview' branch, which requires that 'preview' column in works.csv as well as the feature you recently implemented that allows us to add objects without corresponding BADs to blake-relations.csv

**Comment by nathan-rice** [comment]
You are already sold on git, you should take advantage of it.  All you need to do is have a production branch and say a "next quarterly release" branch, then do all work in the quarterly release and merge once a quarter (or whatever schedule).  Really simple, it avoids adding non-data to the model, it avoids special cases to the code, better all around.

It sounds to me like you are arguing that you guys aren't competent enough handle doing things the right way.  I really hope you guys think better of yourselves than that.

**Comment by ba001** [comment]
@nathan-rice @joeafletch we can't do that because we work on many works at once and only publish some every so often. we can't maintain a 'quarterly' branch as you say. some works, which we work on and collaborate on with people at rochester, don't get published till months in the future, while others get published in a month, for example. @joeafletch can explain

**Comment by nathan-rice** [comment]
Countless teams of programmers - many much larger than your group of editors - collaborate on code bases using git every day.  Frequently, multiple people are modifying single files at the same time.  That is what git was designed for.  Additionally, only one person on your team really needs to know git that well - the one who does the merges.  

I'm sure you don't need to have so many branches that branch management would be burdensome, and by some crazy reason you did, those branches create easily revertible units of work and provide error control, as you can easily see diffs and compare that with commit logs.

Are your editors using git??  If not, that's the first thing you need to fix.

**Comment by ba001** [comment]
another problem with maintaining separate branches is that a blake-relations.csv for each separate branch would get difficult to test and preview

**Comment by nathan-rice** [comment]
Ignoring (and emitting warnings for) relations in blake-relations.csv that don't pass some basic sanity checks is fairly simple.

**Comment by joeafletch** [comment]
@ba001 @nathan-rice I don't have the most nuanced sense of the technical concerns here, but I can say that 1) as frustrating as it might be for all of us, the editors are never going to use git--at this point they can't be bothered to learn new tricks, and we're just lowly grad students and (even worse) postdocs who are in no position to convince them otherwise; and 2) to just reiterate/rephrase what Mike wrote, the editors want the Preview/Testing site to be the repo for all of our works in progress, not just the works we are about to publish in the next quarter. The ideal is to have a bunch of works backlogged on Preview, some in a finished and ready to publish state, some in a more rudimentary state that continues to be refined--then, every time we publish, we would cherrypick the particular copies/works that are finished and scheduled to be moved to Master. We'd like to get (and to some extent already have) a big backlog of ready-to-publish works on Preview that, when it came time to publish each of them, it'd just be a matter of sending them up to Master. We'd like to do most of the editing/uploading images/modifying the blake-relations.csv/etc. well in advance, have it all ready on Preview, so that there wouldn't be much legwork involved when it actually came time to publish. Sorry if I'm repeating myself.

**Comment by ba001** [comment]
i implemented the 'preview' column
