### ISSUE TITLE
links for images in gallery do not have the '100'

### ISSUE THREAD

**Issue by ba001** [blakearchive/archive#480]
@nathan-rice look at any image in the object view, click on it. notice it open in a new window without '100' in the name. for example:

click on the image here:
http://london.lib.unc.edu/copy/mhh.l?descId=mhh.l.illbk.01

notice the opened url:
http://london.lib.unc.edu/images/mhh.l.p1-25..jpg

it should be:
http://london.lib.unc.edu/images/mhh.l.p1-25.100.jpg

**Comment by ba001** [comment]
this has to do with $rootScope.dpivalue

the link is formed based on what dpi value is selected (the buttons just under the menu bar all the way to the right)

**Comment by nathan-rice** [comment]
Somehow my push didn't get all my commits, that and npm watch are both
functional on my local branch.  I'll take care of it when I'm back in the
office.


On Mar 1, 2017 2:30 PM, "ba001" <notifications@github.com> wrote:

this has to do with $rootScope.dpivalue

the link is formed based on what dpi value is selected (the buttons just
under the menu bar all the way to the right)

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/blakearchive/archive/issues/480#issuecomment-283444028>,
or mute the thread

**Comment by ba001** [comment]
fixed this one
