### ISSUE TITLE
Some of the images when clicked lead to blank galleries.

### ISSUE THREAD

**Issue by roastduckalamode** [blakearchive/archive#51]
here's one: http://london.lib.unc.edu/blake/copy/ltapril1800.1

and another:
http://london.lib.unc.edu/blake/copy/but538.1.1xml

for the second one, it looks like an issue with the string at the end. i imagine it should read but538.1.1

**Comment by roastduckalamode** [comment]
@foxm @joeafletch @nathan-rice 

The problem here is the home-page-imges.csv file. It looks like the last column is used to generate the url to the copy. So you'll want to find the correct relative url (in the new site) and place it in this column.

**Comment by nathan-rice** [comment]
Actually, for ltapril1800.1, this is caused by the fact that it is part of a virtual work; in order for the site to not be a special case nightmare (I know, right?), virtual works have a single "virtual copy", and since objects can only have one copy, I have to delete the "normal" copies of works like ltapril1800.1.  If you pull up the debug console, you'll see a 500 error along with those blank galleries, as a result of the server being unable to load the resource.

The solution for cases like lt1pril1800.1 is to change the "bad" for objects in a virtual group to the appropriate virtual work bad.  I could also return a 404 instead of a 500 if an object isn't found, if that would be helpful.

As for the but538 case, the correct bad_id is actually but538.1, not but538.1.1... I've updated that in the home-page-images myself.
