### ISSUE TITLE
scrolling in search preview box is not working on safari

### ISSUE THREAD

**Issue by ba001** [blakearchive/archive#513]
@queryluke luke, do you have any insight into this one by chance? search anything in safari and notice that when you open a search preview box with multiple matching images or a long transcription, you can't scroll down.

**Comment by ba001** [comment]
scroll works in firefox and chrome

**Comment by queryluke** [comment]
seems to be a known bug in safari
http://stackoverflow.com/questions/32971425/overflow-auto-not-working-in-safari-osx
http://stackoverflow.com/questions/35469227/overflow-y-not-working-in-safari-inside-a-modal

you could change the css to `overflow: scroll` instead of `overflow:auto` but this means the scrollbar will always be visible.

**Comment by ba001** [comment]
@queryluke hmm, that didn't seem to work. have a look on london. the scrollbar frame shows but there's no scrollbar. any ideas?

**Comment by queryluke** [comment]
Sorry, that was the only thing I could think of.

FWIW - When I've faced with buggy browser issues, I make a static, local page and slowly peel back the css layers. In this scenario, I'd start with the `div.objects-in-copy`, does scroll work? Add parent div, test, repeat.

**Comment by ba001** [comment]
fixed
